# Generated by Django 2.2.10 on 2020-09-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
