# Generated by Django 2.2.10 on 2020-10-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
