# Generated by Django 2.2.10 on 2020-10-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20201003_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ids', to='adm.ShiftUser'),
        ),
    ]
