# Generated by Django 2.2.10 on 2020-10-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20201003_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
